jasper.sticker.out.dir=
jasper.sticker.table.path=/hr/algebra/cugomatfx/reports/tableSticker.jasper
img.logo.path=/hr/algebra/cugomatfx/images/logos/logo.png
img.background.path=/hr/algebra/cugomatfx/images/background.jpg
cert.keystore.path=/hr/algebra/cugomatfx/keystore/client-CBS.p12
cert.keystore.password=
cert.keystore.type=PKCS12
cert.truststore.path=/hr/algebra/cugomatfx/keystore/client-truststore.jks
cert.truststore.password=
cert.truststore.type=JKS
connection.protocol=TLS
service.url=
jwt.key=

