//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWAEvent.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RWAEvent.WebApp.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ukupnu cijenu.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite trenutnu stranicu .
        /// </summary>
        public static string valCurrentPage {
            get {
                return ResourceManager.GetString("valCurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite email.
        /// </summary>
        public static string valEmail {
            get {
                return ResourceManager.GetString("valEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ispravnu email adresu.
        /// </summary>
        public static string valEmailFormat {
            get {
                return ResourceManager.GetString("valEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite događaj.
        /// </summary>
        public static string valEvent {
            get {
                return ResourceManager.GetString("valEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite listu događaja.
        /// </summary>
        public static string valEventList {
            get {
                return ResourceManager.GetString("valEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite događaje.
        /// </summary>
        public static string valEvents {
            get {
                return ResourceManager.GetString("valEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite tip eventa.
        /// </summary>
        public static string valEventType {
            get {
                return ResourceManager.GetString("valEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite tipove evenata.
        /// </summary>
        public static string valEventTypes {
            get {
                return ResourceManager.GetString("valEventTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite filter.
        /// </summary>
        public static string valFilter {
            get {
                return ResourceManager.GetString("valFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime.
        /// </summary>
        public static string valFirstName {
            get {
                return ResourceManager.GetString("valFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik nije odabran.
        /// </summary>
        public static string valLanguage {
            get {
                return ResourceManager.GetString("valLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite prezime.
        /// </summary>
        public static string valLastName {
            get {
                return ResourceManager.GetString("valLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite lokaciju.
        /// </summary>
        public static string valLocation {
            get {
                return ResourceManager.GetString("valLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite naziv.
        /// </summary>
        public static string valName {
            get {
                return ResourceManager.GetString("valName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite veličinu stranice.
        /// </summary>
        public static string valPageSize {
            get {
                return ResourceManager.GetString("valPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite lozinku.
        /// </summary>
        public static string valPassword {
            get {
                return ResourceManager.GetString("valPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadržavati 8 znakova.
        /// </summary>
        public static string valPasswordSize {
            get {
                return ResourceManager.GetString("valPasswordSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite bar jednog izvođača.
        /// </summary>
        public static string valPerformerList {
            get {
                return ResourceManager.GetString("valPerformerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite izvođače.
        /// </summary>
        public static string valPerformers {
            get {
                return ResourceManager.GetString("valPerformers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite cijenu.
        /// </summary>
        public static string valPrice {
            get {
                return ResourceManager.GetString("valPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ponovljenu lozinku.
        /// </summary>
        public static string valRepeatPassword {
            get {
                return ResourceManager.GetString("valRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka i ponovljena lozinka se ne podudaraju.
        /// </summary>
        public static string valRepeatPasswordMismatch {
            get {
                return ResourceManager.GetString("valRepeatPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovljena lozinka mora sadržavati 8 znakova.
        /// </summary>
        public static string valRepeatPasswordSize {
            get {
                return ResourceManager.GetString("valRepeatPasswordSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite rezervaciju.
        /// </summary>
        public static string valReservation {
            get {
                return ResourceManager.GetString("valReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite listu rezervacija.
        /// </summary>
        public static string valReservations {
            get {
                return ResourceManager.GetString("valReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite status.
        /// </summary>
        public static string valStatus {
            get {
                return ResourceManager.GetString("valStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite listu statusa.
        /// </summary>
        public static string valStatusList {
            get {
                return ResourceManager.GetString("valStatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite broj karata.
        /// </summary>
        public static string valTicketNumber {
            get {
                return ResourceManager.GetString("valTicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite vijeme.
        /// </summary>
        public static string valTime {
            get {
                return ResourceManager.GetString("valTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite naslov.
        /// </summary>
        public static string valTitle {
            get {
                return ResourceManager.GetString("valTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ukupnu cijenu.
        /// </summary>
        public static string valTotal {
            get {
                return ResourceManager.GetString("valTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ukupni broj stranica.
        /// </summary>
        public static string valTotalPages {
            get {
                return ResourceManager.GetString("valTotalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisnika.
        /// </summary>
        public static string valUser {
            get {
                return ResourceManager.GetString("valUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite listu korisnika.
        /// </summary>
        public static string valUserList {
            get {
                return ResourceManager.GetString("valUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime.
        /// </summary>
        public static string valUsername {
            get {
                return ResourceManager.GetString("valUsername", resourceCulture);
            }
        }
    }
}
